// <auto-generated />
using System;
using DbDemo.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbDemo.Core.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20251109192047_Init_Common")]
    partial class Init_Common
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbDemo.Core.Models.Common.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId");

                    b.HasIndex("DistrictId", "Street", "HouseNumber");

                    b.ToTable("Addresses", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidentId");

                    b.HasIndex("AddressId");

                    b.ToTable("Residents", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Company", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Employee", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"));

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndustryId");

                    b.ToTable("Industry", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.HasIndex("CompanyId");

                    b.ToTable("License", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.TaxPayment", b =>
                {
                    b.Property<int>("TaxPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaxPaymentId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TaxPayment", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Class", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.HasIndex("AddressId");

                    b.ToTable("School", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Student", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teacher", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Doctor", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.HasIndex("AddressId");

                    b.ToTable("Hospital", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.MedicalReception", b =>
                {
                    b.Property<int>("MedicalReceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalReceptionId"));

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("MedicalReceptionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ResidentId");

                    b.ToTable("MedicalReception", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Patient", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("NumRooms")
                        .HasColumnType("int");

                    b.HasKey("ApartmentId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartment", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.BillPayment", b =>
                {
                    b.Property<int>("BillPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillPaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilityBillId")
                        .HasColumnType("int");

                    b.HasKey("BillPaymentId");

                    b.HasIndex("UtilityBillId");

                    b.ToTable("BillPayment", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("BuildYear")
                        .HasColumnType("int");

                    b.Property<int>("Floors")
                        .HasColumnType("int");

                    b.Property<int>("NumRooms")
                        .HasColumnType("int");

                    b.HasKey("BuildingId");

                    b.HasIndex("AddressId");

                    b.ToTable("Building", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.ResidentApartment", b =>
                {
                    b.Property<int>("ResidentApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentApartmentId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("ResidentApartmentId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentApartment", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.UtilityBill", b =>
                {
                    b.Property<int>("UtilityBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityBillId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UtilityBillId");

                    b.HasIndex("ApartmentId");

                    b.ToTable("UtilityBill", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Driver", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassengerId");

                    b.HasIndex("ResidentId");

                    b.ToTable("Passenger", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.PassengerTrip", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassengerId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("PassengerTrip", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("Route", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.RouteStop", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "StopId");

                    b.HasIndex("StopId");

                    b.ToTable("RouteStop", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("TripId");

                    b.ToTable("Schedule", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Stop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StopId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StopId");

                    b.HasIndex("AddressId");

                    b.ToTable("Stop", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trip", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicensePlate");

                    b.ToTable("Vehicle", "app");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.Address", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.Resident", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Residents")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Company", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Companies")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Economy.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Employee", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Economy.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Employees")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.License", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Economy.Company", "Company")
                        .WithMany("Licenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.TaxPayment", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Economy.Company", "Company")
                        .WithMany("TaxPayments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Class", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Education.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Education.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.School", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Schools")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Student", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Education.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Students")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Education.School", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolId");

                    b.Navigation("Class");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Teacher", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Teachers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Education.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("School");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Doctor", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Healthcare.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Doctors")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Hospital", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Hospitals")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.MedicalReception", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Healthcare.Doctor", "Doctor")
                        .WithMany("MedicalReceptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Healthcare.Patient", "Patient")
                        .WithMany("MedicalReceptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Common.Resident", null)
                        .WithMany("MedicalReceptions")
                        .HasForeignKey("ResidentId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Patient", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Patients")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Apartment", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Housing.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.BillPayment", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Housing.UtilityBill", "UtilityBill")
                        .WithMany("Payments")
                        .HasForeignKey("UtilityBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtilityBill");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Building", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Buildings")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.ResidentApartment", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Housing.Apartment", "Apartment")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("ResidentApartments")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.UtilityBill", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Housing.Apartment", "Apartment")
                        .WithMany("UtilityBills")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Driver", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Drivers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Passenger", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Resident", "Resident")
                        .WithMany("Passengers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.PassengerTrip", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Transport.Passenger", "Passenger")
                        .WithMany("PassengerTrips")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Transport.Trip", "Trip")
                        .WithMany("PassengerTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.RouteStop", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Transport.Route", "Route")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Transport.Stop", "Stop")
                        .WithMany("RouteStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Schedule", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Transport.Trip", "Trip")
                        .WithMany("Schedules")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Stop", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Common.Address", "Address")
                        .WithMany("Stops")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Trip", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Transport.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbDemo.Core.Models.Transport.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Vehicle", b =>
                {
                    b.HasOne("DbDemo.Core.Models.Transport.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.Address", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Companies");

                    b.Navigation("Hospitals");

                    b.Navigation("Residents");

                    b.Navigation("Schools");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.District", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Common.Resident", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Drivers");

                    b.Navigation("Employees");

                    b.Navigation("MedicalReceptions");

                    b.Navigation("Passengers");

                    b.Navigation("Patients");

                    b.Navigation("ResidentApartments");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Licenses");

                    b.Navigation("TaxPayments");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Economy.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Education.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Doctor", b =>
                {
                    b.Navigation("MedicalReceptions");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Healthcare.Patient", b =>
                {
                    b.Navigation("MedicalReceptions");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Apartment", b =>
                {
                    b.Navigation("Residents");

                    b.Navigation("UtilityBills");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.Building", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Housing.UtilityBill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Driver", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Passenger", b =>
                {
                    b.Navigation("PassengerTrips");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Route", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Stop", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Trip", b =>
                {
                    b.Navigation("PassengerTrips");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DbDemo.Core.Models.Transport.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
